// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rziwebrbzqrqctscssdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6aXdlYnJienFycWN0c2Nzc2R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTE2NzEsImV4cCI6MjA2ODU4NzY3MX0.WMx9RR5A8Qoy4V3T7L7JEFNeKk04bk7Mg7EHXv74brk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});